### ISSUE TITLE
Name suggestions

### ISSUE THREAD

**Issue by HikariKnight** [HikariKnight/quickpassthrough#1]
VFIO-enabler is just a placeholder name.
I am looking for suggestions for proper name for the project.

Some ideas that have been suggested are
* QuickVFIO
* QuickPasstrhough

**Comment by philclifford** [comment]
QuickPassthrough maybe ... :-)

**Comment by HikariKnight** [comment]
> QuickPassthrough maybe ... :-)

a lot of people i asked in my sphere liked QuickPassthrough the most so i decided to change the project name to QuickPassthrough, name is still not set in stone but at least we have the link just in case.
