### ISSUE TITLE
vfio_virqfd module not found

### ISSUE THREAD

**Issue by nowhereandgoodbye** [HikariKnight/quickpassthrough#29]
Does the script still work correctly? I read that vfio_virqfd is now built into the kernel directly?

 -> Running build hook: [fsck]
	==> ERROR: module not found: 'vfio_virqfd'
	==> Generating module dependencies
	==> Creating zstd-compressed initcpio image: '/boot/initramfs-linux-fallback.img'
	==> WARNING: errors were encountered during the build. The image may not be complete

**Comment by HikariKnight** [comment]
can you provide me the debug log?
that part of the code checking the kernel version should not have changed so might be a regression elsewhere

**Comment by HikariKnight** [comment]
Oh actually nvm, the check was missing a dot, next build in a few minutes will fix it @nowhereandgoodbye :)
Thanks for the report as i am still on kernel 6.9 so i would not have experienced the bug.
