### ISSUE TITLE
The doctrine of Useless Cats

### ISSUE THREAD

**Issue by philclifford** [HikariKnight/quickpassthrough#6]
https://github.com/HikariKnight/quickpassthrough/blob/f3c538ee7ed8c3cb5a86527eea9fcfe62fd3ba34/vfio-setup#L11

See [here](https://github.com/koalaman/shellcheck/wiki/SC2002) for the
or you might add `# shellcheck disable=SC2002` as a hint to discourage lots of UUOC feedback

Or just close and ignore this :+1:

**Comment by HikariKnight** [comment]
I will probably disable that shellcheck since it is an option, as new users will understand `cat file` more than `< file`, even though using `< file` is the correct way
